dbt_project:
  outputs:
    dev:
      account: sfseapac-jp_demo23
      database: dbt_hol_2025_dev
      password: 
      role: dbt_hol_role_dev
      schema: public
      threads: 100
      type: snowflake
      user: dbt_user
      warehouse: vwh_dbt_hol_dev
    prod:
      account: sfseapac-jp_demo23
      database: dbt_hol_2025_prod
      password: 
      role: dbt_hol_role_prod
      schema: public
      threads: 100
      type: snowflake
      user: dbt_user
      warehouse: vwh_dbt_hol_prod
  target: dev